const MovieActionType = {    
    REQUEST_MOVIE_PENDING: 'REQUEST_MOVIE_PENDING',
    REQUEST_MOVIE_SUCCESS: 'REQUEST_MOVIE_SUCCESS',
    REQUEST_MOVIE_FAILED: 'REQUEST_MOVIE_FAILED',
    REQUEST_CHARACTERS_PENDING: 'REQUEST_CHARACTERS_PENDING',
    REQUEST_CHARACTERS_SUCCESS: 'REQUEST_CHARACTERS_SUCCESS',
    REQUEST_CHARACTERS_FAILED: 'REQUEST_CHARACTERS_FAILED'
}

export default MovieActionType;